services:
  postgres:
    image: postgres:18
    container_name: insurahub-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./config/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - insurahub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - insurahub-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8025/" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: insurahub-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/insurahub
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH0_ISSUER_URI: ${AUTH0_ISSUER_URI}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_JWK_SET_URI: ${AUTH0_JWK_SET_URI}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_M2M_CLIENT_ID: ${AUTH0_M2M_CLIENT_ID}
      AUTH0_M2M_CLIENT_SECRET: ${AUTH0_M2M_CLIENT_SECRET}
      AUTH0_CONNECTION_NAME: ${AUTH0_CONNECTION_NAME}
      AUTH0_CONSUMER_ROLE: ${AUTH0_CONSUMER_ROLE}
      AUTH0_ADMIN_ROLE: ${AUTH0_ADMIN_ROLE}
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_SENDER: ${MAIL_SENDER}
      MAIL_STARTTLS_ENABLED: false
      MAIL_STARTTLS_REQUIRED: false
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    networks:
      - insurahub-network

volumes:
  postgres_data:

networks:
  insurahub-network:
    driver: bridge
