spring:
  application:
    name: InsuraHub

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    web:
      pageable:
        max-page-size: 100

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
          jwk-set-uri: ${AUTH0_JWK_SET_URI}
          audiences:
            - ${AUTH0_AUDIENCE}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: ${MAIL_STARTTLS_ENABLED:false}
            required: ${MAIL_STARTTLS_REQUIRED:false}

          connectiontimeout: ${MAIL_CONNECTION_TIMEOUT:5000}
          timeout: ${MAIL_TIMEOUT:5000}
          writetimeout: ${MAIL_WRITE_TIMEOUT:5000}

mail:
  sender: ${MAIL_SENDER}

server:
  servlet:
    context-path: /api/v1
  forward-headers-strategy: framework

springdoc:
  cache:
    disabled: true

auth0:
  domain: ${AUTH0_DOMAIN}
  client-id: ${AUTH0_M2M_CLIENT_ID}
  client-secret: ${AUTH0_M2M_CLIENT_SECRET}
  connection-name: ${AUTH0_CONNECTION_NAME}

  role:
    consumer: ${AUTH0_CONSUMER_ROLE}
    admin: ${AUTH0_ADMIN_ROLE}

scalar:
  authentication:
    preferredSecurityScheme: auth0
    oauth2:
      auth0:
        flows:
          password:
            clientId: ${SCALAR_CLIENT_ID}
            tokenUrl: ${SCALAR_TOKEN_URL}
            credentialsLocation: body
