openapi: 3.0.3

info:
  title: InsuraHub API
  version: 1.0.0
  description: |
    REST API for InsuraHub.

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

tags:
  - name: Consumers
    description: Operations related to consumer management
  - name: Packages
    description: Operations related to insurance package management
  - name: Plans
    description: Operations related to plan management
  - name: Claims
    description: Operations related to claim management
  - name: Enrollments
    description: Operations related to enrollments

paths:
  /auth/logout:
    $ref: './authentication/paths.yaml#/logout'
  /consumers:
    $ref: './consumer/paths.yaml#/consumers'
  /consumers/{id}:
    $ref: './consumer/paths.yaml#/consumerById'
  /packages:
    $ref: './package/paths.yaml#/packages'
  /packages/{id}:
    $ref: './package/paths.yaml#/packagesWithId'
  /packages/{packageId}/initialize:
    $ref: './package/paths.yaml#/initializePackage'
  /packages/{packageId}/plans:
    $ref: './plan/paths.yaml#/packagePlans'
  /plans:
    $ref: './plan/paths.yaml#/plans'
  /plans/{id}:
    $ref: './plan/paths.yaml#/planById'
  /claims:
    $ref: './claim/paths.yaml#/claims'
  /claims/{claimId}/approve:
    $ref: './claim/paths.yaml#/claimApprove'
  /claims/{claimId}:
    $ref: './claim/paths.yaml#/claimById'
  /claims/{claimId}/receipt:
    $ref: './claim/paths.yaml#/receiptByClaimId'
  /enrollments:
    $ref: './enrollment/paths.yaml#/enrollments'
  /plans/{planId}/enroll:
    $ref: './enrollment/paths.yaml#/planEnroll'

components:
  securitySchemes:
    auth0:
      type: oauth2
      flows:
        password:
          tokenUrl: https://dev-ah5xlkd4dd1dcyd4.us.auth0.com/oauth/token
          scopes: {}

security:
  - auth0: []
